"""Reference answers, loaded one exercise at a time into notebook globals."""

SOLUTIONS = {
  "matrices": "def incidence(ends, n):\n    A = torch.zeros(len(ends), n, dtype=DTYPE, device=ends.device)\n    rows = torch.arange(len(ends), device=ends.device)\n    A[rows, ends[:, 0]] = 1\n    A[rows, ends[:, 1]] = -1\n    return A\n\ndef nodal_matrix(A, b):\n    return A.T @ (b[:, None] * A)\n",
  "power_flow": "def balance_slack(p_non_slack):\n    return torch.cat([-p_non_slack.sum(-1, keepdim=True), p_non_slack], -1)\n\ndef dc_power_flow(p, A, b):\n    n = A.shape[1]\n    if p.shape[-1] != n:\n        raise ValueError(\"Wrong bus dimension.\")\n    if not torch.allclose(p.sum(-1), torch.zeros_like(p[..., 0]), atol=1e-10, rtol=0):\n        raise ValueError(\"Injections must sum to zero.\")\n    rhs = p[..., 1:].reshape(-1, n-1).T\n    reduced = torch.linalg.solve(nodal_matrix(A, b)[1:, 1:], rhs).T\n    reduced = reduced.reshape(*p.shape[:-1], n-1)\n    theta = torch.cat([torch.zeros_like(p[..., :1]), reduced], -1)\n    return theta, (theta @ A.T) * b\n",
  "cached_solver": "def prepare_solver(A, b):\n    n = A.shape[1]\n    C = torch.linalg.cholesky(nodal_matrix(A, b)[1:, 1:])\n    H = b[:, None] * A\n    def solve(p):\n        if p.shape[-1] != n:\n            raise ValueError(\"Wrong bus dimension.\")\n        rhs = p[..., 1:].reshape(-1, n-1).T\n        reduced = torch.cholesky_solve(rhs, C).T.reshape(*p.shape[:-1], n-1)\n        theta = torch.cat([torch.zeros_like(p[..., :1]), reduced], -1)\n        return theta, theta @ H.T\n    return solve\n",
  "rollout": "def rollout(gain, wind_input):\n    energy = torch.full((wind_input.shape[0],), capacity/2,\n                        dtype=wind_input.dtype, device=wind_input.device)\n    flow_history, action_history, energy_history = [], [], [energy]\n    for t in range(wind_input.shape[1]):\n        requested = gain * (wind_target - wind_input[:, t])\n        lower = torch.maximum(torch.full_like(energy, -power_limit),\n                              (energy-capacity)/dt)\n        upper = torch.minimum(torch.full_like(energy, power_limit), energy/dt)\n        action = torch.minimum(torch.maximum(requested, lower), upper)\n        non_slack = (generation - demand[:, t]\n                     + (wind_input[:, t]+action)[:, None] * wind_bus)\n        _, f = solve(balance_slack(non_slack))\n        energy = energy - action*dt\n        flow_history.append(f)\n        action_history.append(action)\n        energy_history.append(energy)\n    return (torch.stack(flow_history, 1), torch.stack(energy_history, 1),\n            torch.stack(action_history, 1))\n",
  "flow_jvp": "primal_flows, flow_tangent = jvp(flows_only, (p_batch,), (direction,))\n",
  "rollout_jvp": "base_flows, gain_tangent = jvp(gain_to_flows, (gain,), (torch.ones_like(gain),))\nscore, score_tangent = jvp(loading_score, (gain,), (torch.ones_like(gain),))\n",
  "outages": "def connected_after_outage(ends, n, outage):\n    adjacency = [[] for _ in range(n)]\n    for k, (i, j) in enumerate(ends.cpu().tolist()):\n        if k != outage:\n            adjacency[i].append(j)\n            adjacency[j].append(i)\n    visited, pending = {0}, [0]\n    while pending:\n        i = pending.pop()\n        for j in adjacency[i]:\n            if j not in visited:\n                visited.add(j)\n                pending.append(j)\n    return len(visited) == n\n\ndef outage_loading(p_batch, A, b, limits):\n    results = []\n    for k in range(len(b)):\n        if not connected_after_outage(ends, A.shape[1], k):\n            results.append(torch.full(p_batch.shape[:-1], float(\"nan\"),\n                                      dtype=p_batch.dtype, device=p_batch.device))\n            continue\n        b_outage = b.clone()\n        b_outage[k] = 0\n        outage_solve = prepare_solver(A, b_outage)\n        _, f = outage_solve(p_batch)\n        torch.testing.assert_close(f @ A, p_batch)\n        torch.testing.assert_close(f[..., k], torch.zeros_like(f[..., k]))\n        results.append((f.abs()/limits).amax(-1))\n    return torch.stack(results)\n",
  "benchmark": "def benchmark():\n    print(\"scenarios | loop ms | batch ms | speedup\")\n    for size in [1, 32, 256, 2048]:\n        q = balance_slack(torch.randn(size, N-1, dtype=DTYPE, device=DEVICE)*0.25)\n        def loop():\n            return torch.stack([solve(row)[1] for row in q])\n        def batch():\n            return solve(q)[1]\n        torch.testing.assert_close(loop(), batch())\n        with torch.no_grad():\n            t_loop, t_batch = median_time(loop), median_time(batch)\n        print(f\"{size:9d} | {t_loop*1000:7.3f} | {t_batch*1000:8.3f} | {t_loop/t_batch:7.2f}\")\n"
}
